# -*- coding: utf-8 -*-
"""Symmetric.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ldYFIepYT6jEA5rkkisO1UPUK4UdJ9qZ

SİMETRİK ŞİFRELEME
"""

!pip install pycrypto

from Crypto.Cipher import DES,AES
from Crypto import Random

"""DES ve AES için anahtarlar belirlendi"""

desKey = b"SECURITY" # DES 64 bit
aesKey = b"SECURITYSECURITY"  # AES 128 bit

metin = input("Şifrelenecek Metni Giriniz: ")
plain = bytes(metin,encoding = "utf-8")



"""##DES için şifreleme

#### Padding
"""

kalan = len(plain) % 8
if kalan != 0:
  for i in range(8-kalan):
    plain += b"-"
else:
  print("Metin Tam Şifrelenebilir")

iv = Random.new().read(DES.block_size)
desCipher = DES.new(desKey, DES.MODE_ECB,iv)

desCipherMsg = desCipher.encrypt(plain)

"""Şifreli Metin"""

sifreliMetin1 = desCipherMsg.decode('latin-1')
sifreliMetin1

"""Şifresi Çözülmüş Metin"""

msgDes = desCipher.decrypt(desCipherMsg)

duzMetin1 = msgDes.decode()
duzMetin1 = duzMetin1.replace("-","")
duzMetin1

"""##AES için şifreleme

Padding
"""

kalan = len(plain) % 16
if kalan != 0:
  for i in range(16-kalan):
    plain += b"-"
else:
  print("Metin Tam Şifrelenebilir")

iv = Random.new().read(AES.block_size)
aesCipher = AES.new(aesKey, AES.MODE_ECB,iv)

"""Şifreli Metin"""

aesCipherMsg = aesCipher.encrypt(plain)

sifreliMetin2 = aesCipherMsg.decode('latin-1')
sifreliMetin2

"""Şifresi Çözülmüş Metin"""

msgAes = aesCipher.decrypt(aesCipherMsg)

duzMetin2 = msgAes.decode()
duzMetin2 = duzMetin2.replace("-","")
duzMetin2